from pathlib import Path

from ..diff import geometry_diff
from ..versioning import MICROCOSM_VERSION, SCHEMA_VERSION, GENERATOR_VERSION
from .operators import (
    expert_judgments,
    finding_delta_ids,
    forecast_from_findings,
    verify_forecast_check,
)
from .state import summarize_state
from .transitions import make_transition, observed_events, planned_events


TEMPORAL_PURPOSE = (
    "Find the smallest fastest feasible implementation path by compressing "
    "structural exploration and deep decision-making into a pre-change or "
    "post-change report."
)


def build_static_report(project_root, run_id, mir, decision, risk, mode="inspect"):
    findings = mir.get("findings", [])
    delta = {"resolved": [], "new": [], "still_open": findings}
    forecast = forecast_from_findings(mode, decision, risk, delta, findings)
    return _base_report(project_root, run_id, mode, mir, decision, risk, [
        summarize_state("state.current", "current", mir),
    ], [], [], forecast, None)


def build_plan_report(project_root, run_id, plan, before_mir, projected_mir, preview_diff, risk, decision):
    before = dict(before_mir)
    after = dict(projected_mir)
    events = planned_events(plan)
    geometry = geometry_diff(before, after)
    finding_delta = finding_delta_ids(preview_diff)
    transition = make_transition(
        "transition.plan.{}".format((plan or {}).get("id") or run_id),
        "state.current",
        "state.projected",
        [event["id"] for event in events],
        geometry,
        finding_delta,
        "planned",
    )
    forecast = forecast_from_findings("plan-change", decision, risk, preview_diff, after.get("findings", []))
    return _base_report(project_root, run_id, "plan-change", before, decision, risk, [
        summarize_state("state.current", "current", before),
        summarize_state("state.projected", "projected", after),
    ], events, [transition], forecast, None)


def build_verify_report(project_root, run_id, baseline_mir, current_mir, verify_diff, risk, decision):
    events = observed_events(verify_diff)
    finding_delta = finding_delta_ids((verify_diff or {}).get("findings", {}))
    transition = make_transition(
        "transition.verify.{}".format(run_id),
        "state.baseline",
        "state.current",
        [event["id"] for event in events],
        (verify_diff or {}).get("geometry", {}),
        finding_delta,
        "observed",
    )
    actual_delta = {
        "resolved": (verify_diff or {}).get("findings", {}).get("resolved", []),
        "new": (verify_diff or {}).get("findings", {}).get("new", []),
        "still_open": (verify_diff or {}).get("findings", {}).get("still_open", []),
    }
    forecast = forecast_from_findings("verify", decision, risk, actual_delta, current_mir.get("findings", []))
    forecast_check = verify_forecast_check(project_root, verify_diff)
    return _base_report(project_root, run_id, "verify", current_mir, decision, risk, [
        summarize_state("state.baseline", "baseline", baseline_mir),
        summarize_state("state.current", "current", current_mir),
    ], events, [transition], forecast, forecast_check)


def simulate(*args, **kwargs):
    return (
        "Direct temporal scenario execution is not available. "
        "Temporal reports are generated by inspect, plan-change, and verify."
    )


def _base_report(project_root, run_id, mode, mir, decision, risk, states, events, transitions, forecast, forecast_check):
    payload = {
        "microcosm_version": MICROCOSM_VERSION,
        "schema_version": SCHEMA_VERSION,
        "generator_version": GENERATOR_VERSION,
        "run_id": run_id,
        "mode": mode,
        "project_root": str(Path(project_root)),
        "purpose": TEMPORAL_PURPOSE,
        "states": states,
        "events": events,
        "transitions": transitions,
        "forecast": forecast,
        "expert_judgment": expert_judgments(mode, forecast, forecast_check),
        "limits": [
            "Deterministic temporal report only; no business outcome simulation.",
            "Forecasts are derived from MIR geometry, findings, policies, and evidence.",
            "Runtime trace ingestion is still limited unless explicit trace data is provided.",
        ],
    }
    if forecast_check is not None:
        payload["forecast_check"] = forecast_check
    return payload
